services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sup1nf0
      MYSQL_DATABASE: wordpressdb
    ports:
      - "3306:3306"
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Sup1nf0
      WORDPRESS_DB_NAME: wordpressdb
    ports:
      - "8080:80"
    networks:
      - wordpress-network

networks:
  wordpress-network: